In [151]:
import pandas as pd
import numpy as np
import vaex



# Reading the data from CSV file

In [152]:
df = pd.read_csv("resources/tmdb_5000_movies.csv")


In [153]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [154]:
df.head(100)

budget                                             genres  \
0   237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1   300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2   245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3   250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4   260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
..        ...                                                ...   
95  165000000  [{"id": 12, "name": "Adventure"}, {"id": 18, "...   
96  160000000  [{"id": 28, "name": "Action"}, {"id": 53, "nam...   
97   15000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
98  250000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
99   38000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   

                                        homepage      id  \
0                    http://www.avatarmovie.com/   19995   
1   http://disney.go.com/disneypictures/pirates/     285   
2    http://www.sonypictures.com/movies/spectre/  206647   
3             http://www.thedarkknightrises.com/   49026   
4           http://movies.disney.com/john-carter   49529   
..                                           ...     ...   
95             http://www.interstellarmovie.net/  157336   
96         http://inceptionmovie.warnerbros.com/   27205   
97                                           NaN  315011   
98                     http://www.thehobbit.com/   49051   
99                                           NaN    9799   

                                             keywords original_language  \
0   [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1   [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2   [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3   [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4   [{"id": 818, "name": "based on novel"}, {"id":...                en   
..                                                ...               ...   
95  [{"id": 83, "name": "saving the world"}, {"id"...                en   
96  [{"id": 1014, "name": "loss of lover"}, {"id":...                en   
97  [{"id": 1299, "name": "monster"}, {"id": 7671,...                ja   
98  [{"id": 483, "name": "riddle"}, {"id": 603, "n...                en   
99  [{"id": 542, "name": "street gang"}, {"id": 83...                en   

                              original_title  \
0                                     Avatar   
1   Pirates of the Caribbean: At World's End   
2                                    Spectre   
3                      The Dark Knight Rises   
4                                John Carter   
..                                       ...   
95                              Interstellar   
96                                 Inception   
97                                    シン・ゴジラ   
98         The Hobbit: An Unexpected Journey   
99                  The Fast and the Furious   

                                             overview  popularity  \
0   In the 22nd century, a paraplegic Marine is di...  150.437577   
1   Captain Barbossa, long believed to be dead, ha...  139.082615   
2   A cryptic message from Bond’s past sends him o...  107.376788   
3   Following the death of District Attorney Harve...  112.312950   
4   John Carter is a war-weary, former military ca...   43.926995   
..                                                ...         ...   
95  Interstellar chronicles the adventures of a gr...  724.247784   
96  Cobb, a skilled thief who commits corporate es...  167.583710   
97  From the mind behind Evangelion comes a hit la...    9.476999   
98  Bilbo Baggins, a hobbit enjoying his quiet lif...  108.849621   
99  Domenic Toretto is a Los Angeles street racer ...    6.909942   

                                 production_companies  \
0   [{"name": "Ingenious Film Partners", "id": 289...   
1   [{"name": "Walt Disney Pictures", "id": 2}, 

# Cleaning Data

### Replacing Languaeg Codes with Proper Names

In [155]:
df.original_language.unique()

array(['en', 'ja', 'fr', 'zh', 'es', 'de', 'hi', 'ru', 'ko', 'te', 'cn',
       'it', 'nl', 'ta', 'sv', 'th', 'da', 'xx', 'hu', 'cs', 'pt', 'is',
       'tr', 'nb', 'af', 'pl', 'he', 'ar', 'vi', 'ky', 'id', 'ro', 'fa',
       'no', 'sl', 'ps', 'el'], dtype=object)

In [156]:
from langcodes import *

In [157]:
def get_lang(data):
    return Language.make(language=f'{data}').display_name()

In [158]:
df.original_language = df.original_language.map(lambda x: get_lang(x))

In [159]:
df

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...           English   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...           English   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...           English   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...           English   
4     [{"id": 818, "name": "based on novel"}, {"id":...           English   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...           Spanish   
4799                                                 []           English   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...           English   
4801                                                 []           English   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...           English   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ... 

In [160]:
df.original_language.unique()

array(['English', 'Japanese', 'French', 'Chinese', 'Spanish', 'German',
       'Hindi', 'Russian', 'Korean', 'Telugu', 'Unknown language [cn]',
       'Italian', 'Dutch', 'Tamil', 'Swedish', 'Thai', 'Danish',
       'Unknown language [xx]', 'Hungarian', 'Czech', 'Portuguese',
       'Icelandic', 'Turkish', 'Norwegian Bokmål', 'Afrikaans', 'Polish',
       'Hebrew', 'Arabic', 'Vietnamese', 'Kyrgyz', 'Indonesian',
       'Romanian', 'Persian', 'Norwegian', 'Slovenian', 'Pashto', 'Greek'],
      dtype=object)

In [161]:
df['original_language'] = df['original_language'].replace(['Unknown language [cn]','Unknown language [xx]'],['Unknown','Unknown'])

In [162]:
df.original_language.unique()

array(['English', 'Japanese', 'French', 'Chinese', 'Spanish', 'German',
       'Hindi', 'Russian', 'Korean', 'Telugu', 'Unknown', 'Italian',
       'Dutch', 'Tamil', 'Swedish', 'Thai', 'Danish', 'Hungarian',
       'Czech', 'Portuguese', 'Icelandic', 'Turkish', 'Norwegian Bokmål',
       'Afrikaans', 'Polish', 'Hebrew', 'Arabic', 'Vietnamese', 'Kyrgyz',
       'Indonesian', 'Romanian', 'Persian', 'Norwegian', 'Slovenian',
       'Pashto', 'Greek'], dtype=object)

In [163]:
df

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...           English   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...           English   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...           English   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...           English   
4     [{"id": 818, "name": "based on novel"}, {"id":...           English   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...           Spanish   
4799                                                 []           English   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...           English   
4801                                                 []           English   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...           English   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ... 

In [171]:
df.describe()

budget             id   popularity       revenue      runtime  \
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03  4801.000000   
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07   106.875859   
std    4.072239e+07   88694.614033    31.816650  1.628571e+08    22.611935   
min    0.000000e+00       5.000000     0.000000  0.000000e+00     0.000000   
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00    94.000000   
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07   103.000000   
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07   118.000000   
max    3.800000e+08  459488.000000   875.581305  2.787965e+09   338.000000   

       vote_average    vote_count  
count   4803.000000   4803.000000  
mean       6.092172    690.217989  
std        1.194612   1234.585891  
min        0.000000      0.000000  
25%        5.600000     54.000000  
50%        6.200000    235.000000  
75%        6.800000    737.000000  
max       10.000000  13752.000000

In [173]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///resources/data.db', echo=False)

In [174]:
df.to_sql('info', con=engine, if_exists='append')

### Machine Learning 

In [5]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
df = pd.read_csv("resources/movies.csv")
df

index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction   
1         1  300000000                  Adventure Fantasy Action   
2         2  245000000                    Action Adventure Crime   
3         3  250000000               Action Crime Drama Thriller   
4         4  260000000          Action Adventure Science Fiction   
...     ...        ...                                       ...   
1134   1134   48000000           Adventure Comedy Family Fantasy   
1135   1135   42000000                      Crime Drama Thriller   
1136   1136   31000000            Drama Adventure Action History   
1137   1137   40000000                       Action Comedy Crime   
1138   1138   44000000                             Action Comedy   

                                           homepage      id  \
0                       http://www.avatarmovie.com/   19995   
1      http://disney.go.com/disneypictures/pirates/     285   
2       http://www.sonypictures.com/movies/spectre/  206647   
3                http://www.thedarkknightrises.com/   49026   
4              http://movies.disney.com/john-carter   49529   
...                                             ...     ...   
1134                                            NaN    9607   
1135                                            NaN    1830   
1136                                            NaN      79   
1137  http://www.oneforthemoneyfilm.com/index2.html   54054   
1138                                            NaN  228967   

                                               keywords original_language  \
0     culture clash future space war space colony so...                en   
1     ocean drug abuse exotic island east india trad...                en   
2            spy based on novel secret agent sequel mi6                en   
3     dc comics crime fighter terrorist secret ident...                en   
4     based on novel mars medallion space travel pri...                en   
...                                                 ...               ...   
1134  saving the world brother brother relationship ...                en   
1135                        cold war weapon arms dealer                en   
1136  countryside loss of lover right and justice pa...                zh   
1137  bounty hunter based on novel romance framed ba...                en   
1138  cia coup d'etat north korea assassination atte...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
1134                         Super Mario Bros.   
1135                               Lord of War   
1136                                        英雄   
1137                         One for the Money   
1138                             The Interview   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
1134  Mario and Luigi, plumbers from Brooklyn, find ...   14.587367  ...   
1135  Yuri Orlov is a globetrotting arms dealer and,...   34.828241  ...   
1136  One man defeated three assassins who sought to...   23.607392  ...   
1137  An unemployed lingerie buyer convinces her bai...   19.438503  ...   
1138  Dave Skylark and his producer Aaron Rapoport r...   74.168016  .

In [12]:


features = ['keywords', 'cast', 'genres', 'director']
for feature in features:
    df[feature] = df[feature].fillna('')

In [13]:
def combined_features(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']
df["combined_features"] = df.apply(combined_features, axis =1)

In [14]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
cosine_sim = cosine_similarity(count_matrix)

In [31]:
movie_user_likes = "The Dark Knight Rises"
def get_index_from_title(title):
    value = df.index[df['title'] == title].tolist()
    return value[0]
movie_index = get_index_from_title(movie_user_likes)
movie_index

3

In [34]:
similar_movies = list(enumerate(cosine_sim[movie_index]))
similar_movies
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)
sorted_similar_movies

 (528, 0.12267912301642962),
 (544, 0.12267912301642962),
 (570, 0.12267912301642962),
 (589, 0.12267912301642962),
 (652, 0.12267912301642962),
 (746, 0.12267912301642962),
 (823, 0.12267912301642962),
 (876, 0.12267912301642962),
 (924, 0.12267912301642962),
 (929, 0.12267912301642962),
 (955, 0.12267912301642962),
 (1025, 0.12267912301642962),
 (1030, 0.12267912301642962),
 (1045, 0.12267912301642962),
 (1116, 0.12267912301642962),
 (1132, 0.12267912301642962),
 (9, 0.12009611535381537),
 (281, 0.12009611535381537),
 (312, 0.12009611535381537),
 (346, 0.12009611535381537),
 (356, 0.12009611535381537),
 (548, 0.12009611535381537),
 (596, 0.12009611535381537),
 (660, 0.12009611535381537),
 (684, 0.12009611535381537),
 (735, 0.12009611535381537),
 (809, 0.12009611535381537),
 (1018, 0.12009611535381537),
 (10, 0.11766968108291043),
 (104, 0.11766968108291043),
 (149, 0.11766968108291043),
 (247, 0.11766968108291043),
 (271, 0.11766968108291043),
 (275, 0.11766968108291043),
 (285, 0.11

In [33]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
i=0
for movie in sorted_similar_movies:
    print(get_title_from_index(movie[0]))
    i=i+1
    if i>15:
        break

The Dark Knight Rises
Batman Begins
The Dark Knight
Batman Returns
Batman & Robin
Child 44
Interstellar
Superman
Murder by Numbers
Man on Fire
The Bone Collector
Jack Reacher
Law Abiding Citizen
Patriot Games
London Has Fallen
Dick Tracy
