In [1]:
import pandas as pd
import numpy as np
# import vaex



# Reading the data from CSV file

In [2]:
df = pd.read_csv("resources/movies.csv")


In [3]:
df.isnull().sum()

index                     0
budget                    0
genres                    0
homepage                570
id                        0
keywords                 17
original_language         0
original_title            0
overview                  0
popularity                0
production_companies      0
production_countries      0
release_date              0
revenue                   0
runtime                   0
spoken_languages          0
status                    0
tagline                  44
title                     0
vote_average              0
vote_count                0
cast                      0
crew                      0
director                  7
dtype: int64

In [4]:
df.shape

(1139, 24)

In [5]:
df.head(100)

index     budget                                             genres  \
0       0  237000000           Action Adventure Fantasy Science Fiction   
1       1  300000000                           Adventure Fantasy Action   
2       2  245000000                             Action Adventure Crime   
3       3  250000000                        Action Crime Drama Thriller   
4       4  260000000                   Action Adventure Science Fiction   
..    ...        ...                                                ...   
95     95  165000000                    Adventure Drama Science Fiction   
96     96  160000000  Action Thriller Science Fiction Mystery Adventure   
97     97   15000000      Action Adventure Drama Horror Science Fiction   
98     98  250000000                           Adventure Fantasy Action   
99     99   38000000                              Action Crime Thriller   

                                        homepage      id  \
0                    http://www.avatarmovie.com/   19995   
1   http://disney.go.com/disneypictures/pirates/     285   
2    http://www.sonypictures.com/movies/spectre/  206647   
3             http://www.thedarkknightrises.com/   49026   
4           http://movies.disney.com/john-carter   49529   
..                                           ...     ...   
95             http://www.interstellarmovie.net/  157336   
96         http://inceptionmovie.warnerbros.com/   27205   
97                                           NaN  315011   
98                     http://www.thehobbit.com/   49051   
99                                           NaN    9799   

                                             keywords original_language  \
0   culture clash future space war space colony so...                en   
1   ocean drug abuse exotic island east india trad...                en   
2          spy based on novel secret agent sequel mi6                en   
3   dc comics crime fighter terrorist secret ident...                en   
4   based on novel mars medallion space travel pri...                en   
..                                                ...               ...   
95  saving the world artificial intelligence fathe...                en   
96  loss of lover dream kidnapping sleep subconsci...                en   
97   monster godzilla giant monster destruction kaiju                ja   
98   riddle elves dwarves orcs middle-earth (tolkien)                en   
99  street gang car race undercover auto-tuning lo...                en   

                              original_title  \
0                                     Avatar   
1   Pirates of the Caribbean: At World's End   
2                                    Spectre   
3                      The Dark Knight Rises   
4                                John Carter   
..                                       ...   
95                              Interstellar   
96                                 Inception   
97                                    シン・ゴジラ   
98         The Hobbit: An Unexpected Journey   
99                  The Fast and the Furious   

                                             overview  popularity  ...  \
0   In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1   Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2   A cryptic message from Bond’s past sends him o...  107.376788  ...   
3   Following the death of District Attorney Harve...  112.312950  ...   
4   John Carter is a war-weary, former military ca...   43.926995  ...   
..                                                ...         ...  ...   
95  Interstellar chronicles the adventures of a gr...  724.247784  ...   
96  Cobb, a skilled thief who commits corporate es...  167.583710  ...   
97  From the mind behind Evangelion comes a hit la...    9.476999  ...   
98  Bilbo Baggins, a hobbit enjoying his quiet lif...  108.849621  ...   
99  Domenic Toretto is a Los Angeles street racer ...    6.909942  ...   

   runtime     

# Cleaning Data

### Replacing Languaeg Codes with Proper Names

In [6]:
df.original_language.unique()

array(['en', 'ja', 'fr', 'zh', 'es', 'de', 'hi', 'ru'], dtype=object)

In [7]:
from langcodes import *

In [8]:
def get_lang(data):
    return Language.make(language=f'{data}').display_name()

In [9]:
df.original_language = df.original_language.map(lambda x: get_lang(x))

In [10]:
df

index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction   
1         1  300000000                  Adventure Fantasy Action   
2         2  245000000                    Action Adventure Crime   
3         3  250000000               Action Crime Drama Thriller   
4         4  260000000          Action Adventure Science Fiction   
...     ...        ...                                       ...   
1134   1134   48000000           Adventure Comedy Family Fantasy   
1135   1135   42000000                      Crime Drama Thriller   
1136   1136   31000000            Drama Adventure Action History   
1137   1137   40000000                       Action Comedy Crime   
1138   1138   44000000                             Action Comedy   

                                           homepage      id  \
0                       http://www.avatarmovie.com/   19995   
1      http://disney.go.com/disneypictures/pirates/     285   
2       http://www.sonypictures.com/movies/spectre/  206647   
3                http://www.thedarkknightrises.com/   49026   
4              http://movies.disney.com/john-carter   49529   
...                                             ...     ...   
1134                                            NaN    9607   
1135                                            NaN    1830   
1136                                            NaN      79   
1137  http://www.oneforthemoneyfilm.com/index2.html   54054   
1138                                            NaN  228967   

                                               keywords original_language  \
0     culture clash future space war space colony so...           English   
1     ocean drug abuse exotic island east india trad...           English   
2            spy based on novel secret agent sequel mi6           English   
3     dc comics crime fighter terrorist secret ident...           English   
4     based on novel mars medallion space travel pri...           English   
...                                                 ...               ...   
1134  saving the world brother brother relationship ...           English   
1135                        cold war weapon arms dealer           English   
1136  countryside loss of lover right and justice pa...           Chinese   
1137  bounty hunter based on novel romance framed ba...           English   
1138  cia coup d'etat north korea assassination atte...           English   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
1134                         Super Mario Bros.   
1135                               Lord of War   
1136                                        英雄   
1137                         One for the Money   
1138                             The Interview   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
1134  Mario and Luigi, plumbers from Brooklyn, find ...   14.587367  ...   
1135  Yuri Orlov is a globetrotting arms dealer and,...   34.828241  ...   
1136  One man defeated three assassins who sought to...   23.607392  ...   
1137  An unemployed lingerie buyer convinces her bai...   19.438503  ...   
1138  Dave Skylark and his producer Aaron Rapoport r...   74.168016  .

In [11]:
df.original_language.unique()

array(['English', 'Japanese', 'French', 'Chinese', 'Spanish', 'German',
       'Hindi', 'Russian'], dtype=object)

In [12]:
df['original_language'] = df['original_language'].replace(['Unknown language [cn]','Unknown language [xx]'],['Unknown','Unknown'])

In [13]:
df.original_language.unique()

array(['English', 'Japanese', 'French', 'Chinese', 'Spanish', 'German',
       'Hindi', 'Russian'], dtype=object)

In [14]:
df

index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction   
1         1  300000000                  Adventure Fantasy Action   
2         2  245000000                    Action Adventure Crime   
3         3  250000000               Action Crime Drama Thriller   
4         4  260000000          Action Adventure Science Fiction   
...     ...        ...                                       ...   
1134   1134   48000000           Adventure Comedy Family Fantasy   
1135   1135   42000000                      Crime Drama Thriller   
1136   1136   31000000            Drama Adventure Action History   
1137   1137   40000000                       Action Comedy Crime   
1138   1138   44000000                             Action Comedy   

                                           homepage      id  \
0                       http://www.avatarmovie.com/   19995   
1      http://disney.go.com/disneypictures/pirates/     285   
2       http://www.sonypictures.com/movies/spectre/  206647   
3                http://www.thedarkknightrises.com/   49026   
4              http://movies.disney.com/john-carter   49529   
...                                             ...     ...   
1134                                            NaN    9607   
1135                                            NaN    1830   
1136                                            NaN      79   
1137  http://www.oneforthemoneyfilm.com/index2.html   54054   
1138                                            NaN  228967   

                                               keywords original_language  \
0     culture clash future space war space colony so...           English   
1     ocean drug abuse exotic island east india trad...           English   
2            spy based on novel secret agent sequel mi6           English   
3     dc comics crime fighter terrorist secret ident...           English   
4     based on novel mars medallion space travel pri...           English   
...                                                 ...               ...   
1134  saving the world brother brother relationship ...           English   
1135                        cold war weapon arms dealer           English   
1136  countryside loss of lover right and justice pa...           Chinese   
1137  bounty hunter based on novel romance framed ba...           English   
1138  cia coup d'etat north korea assassination atte...           English   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
1134                         Super Mario Bros.   
1135                               Lord of War   
1136                                        英雄   
1137                         One for the Money   
1138                             The Interview   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
1134  Mario and Luigi, plumbers from Brooklyn, find ...   14.587367  ...   
1135  Yuri Orlov is a globetrotting arms dealer and,...   34.828241  ...   
1136  One man defeated three assassins who sought to...   23.607392  ...   
1137  An unemployed lingerie buyer convinces her bai...   19.438503  ...   
1138  Dave Skylark and his producer Aaron Rapoport r...   74.168016  .

In [15]:
df.describe()

index        budget             id   popularity       revenue  \
count  1139.000000  1.139000e+03    1139.000000  1139.000000  1.139000e+03   
mean    569.000000  8.438745e+07   41709.043898    42.837096  2.340926e+08   
std     328.945284  4.899703e+07   70673.129647    52.113779  2.588354e+08   
min       0.000000  0.000000e+00      12.000000     0.146783  0.000000e+00   
25%     284.500000  5.200000e+07    3832.000000    18.104296  6.721274e+07   
50%     569.000000  7.000000e+07   10201.000000    31.435539  1.554644e+08   
75%     853.500000  1.000000e+08   45093.000000    51.502639  3.036729e+08   
max    1138.000000  3.800000e+08  417859.000000   875.581305  2.787965e+09   

           runtime  vote_average    vote_count  
count  1139.000000   1139.000000   1139.000000  
mean    115.711150      6.207638   1612.542581  
std      22.034523      0.807654   1901.655200  
min       0.000000      2.300000      1.000000  
25%     100.000000      5.700000    388.500000  
50%     114.000000      6.200000    915.000000  
75%     128.000000      6.700000   2056.000000  
max     248.000000      8.300000  13752.000000

In [16]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///resources/data.db', echo=False)

In [17]:
df.to_sql('info', con=engine, if_exists='append')

### Machine Learning 

In [18]:
# import pandas as pd
# import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
# df = pd.read_csv("resources/movies.csv")
# df

In [20]:


features = ['keywords', 'cast', 'genres', 'director']
for feature in features:
    df[feature] = df[feature].fillna('')

In [21]:
def combined_features(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']
df["combined_features"] = df.apply(combined_features, axis =1)

In [31]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [33]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim

array([[1.        , 0.10540926, 0.12038585, ..., 0.0727393 , 0.03849002,
        0.08399211],
       [0.10540926, 1.        , 0.0761387 , ..., 0.10350983, 0.03651484,
        0.03984095],
       [0.12038585, 0.0761387 , 1.        , ..., 0.07881104, 0.2502173 ,
        0.04550158],
       ...,
       [0.0727393 , 0.10350983, 0.07881104, ..., 1.        , 0.03779645,
        0.0412393 ],
       [0.03849002, 0.03651484, 0.2502173 , ..., 0.03779645, 1.        ,
        0.08728716],
       [0.08399211, 0.03984095, 0.04550158, ..., 0.0412393 , 0.08728716,
        1.        ]])

In [35]:
movie_user_likes = "The Dark Knight Rises"
def get_index_from_title(title):
    value = df.index[df['title'] == title].tolist()
    return value[0]
movie_index = get_index_from_title(movie_user_likes)
movie_index

3

In [30]:
recommnedations =[]

def get_title_from_index(index):
     recommnedations.append(df[df.index == index])
for movie in sorted_similar_movies:
    get_title_from_index(movie[0])
print(recommnedations[1:15])


AttributeError: 'DataFrame' object has no attribute 'to_list'

In [25]:
similar_movies = list(enumerate(cosine_sim[movie_index]))
similar_movies
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)
sorted_similar_movies

 (528, 0.12267912301642962),
 (544, 0.12267912301642962),
 (570, 0.12267912301642962),
 (589, 0.12267912301642962),
 (652, 0.12267912301642962),
 (746, 0.12267912301642962),
 (823, 0.12267912301642962),
 (876, 0.12267912301642962),
 (924, 0.12267912301642962),
 (929, 0.12267912301642962),
 (955, 0.12267912301642962),
 (1025, 0.12267912301642962),
 (1030, 0.12267912301642962),
 (1045, 0.12267912301642962),
 (1116, 0.12267912301642962),
 (1132, 0.12267912301642962),
 (9, 0.12009611535381537),
 (281, 0.12009611535381537),
 (312, 0.12009611535381537),
 (346, 0.12009611535381537),
 (356, 0.12009611535381537),
 (548, 0.12009611535381537),
 (596, 0.12009611535381537),
 (660, 0.12009611535381537),
 (684, 0.12009611535381537),
 (735, 0.12009611535381537),
 (809, 0.12009611535381537),
 (1018, 0.12009611535381537),
 (10, 0.11766968108291043),
 (104, 0.11766968108291043),
 (149, 0.11766968108291043),
 (247, 0.11766968108291043),
 (271, 0.11766968108291043),
 (275, 0.11766968108291043),
 (285, 0.11

In [28]:
from sqlalchemy import create_engine
searchbox = "Batman"
engine = create_engine('sqlite:///resources/data.db', echo=False)
connection = engine.connect()
# sql_data = engine.execute("""SELECT title FROM info WHERE title LIKE ?""", ('%'+searchbox+'%', ))
sql_data = engine.execute(f"SELECT title FROM info WHERE title LIKE '%{searchbox}%' order by title")
# print(data)
data = []
for items in sql_data:
    data.append(items)
print(data)


[('Batman & Robin',), ('Batman & Robin',), ('Batman Begins',), ('Batman Begins',), ('Batman Forever',), ('Batman Forever',), ('Batman Returns',), ('Batman Returns',), ('Batman v Superman: Dawn of Justice',), ('Batman v Superman: Dawn of Justice',)]
